name: dockman
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  http: ^1.3.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.11.1
  introduction_screen: ^3.1.17
  firebase_core: ^3.13.0
  local_auth: ^2.3.0
  url_launcher: ^6.3.1
  flutter_hooks: ^0.21.2
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0
  build_runner: any
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/docker.svg
    - assets/dockman.svg
    - assets/portainer.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dockman.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1D63ED"
  adaptive_icon_foreground: "assets/dockman_mono.png"
  adaptive_icon_monochrome: "assets/dockman_mono.png"
  web:
    generate: true
    background_color: "#1D63ED"
    theme_color: "#1D63ED"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true
